dradis/dradis-plugins

CHANGELOG.md, lib/dradis/plugins/content_service/core.rb, lib/dradis/plugins/content_service/issues.rb, lib/dradis/plugins/gem_version.rb
When importing an issue with text that exceeds the possible length, the app tries to truncate it. This results in the plugin details to be truncated too.
**Proposed solution**
Re-insert the plugin details after truncation.
1. Install the Netsparker plugin in your Gemfile. https://github.com/dradis/dradis-netsparker
2. Get a netsparker XML.
3. Go to "Upload output from tool in the app" in Dradis
4. Upload the downloaded XML using the Netsparker plugin
5. Assert that there are no errors and the upload is successful.
=> fix-truncate

lib/dradis/plugins/content_service/properties.rb
For the report content feature, we're phasing out the old style of document properties.
=> Use Node content library for properties

lib/dradis/plugins/content_service/content_blocks.rb, lib/dradis/plugins/content_service/nodes.rb, lib/dradis/plugins/upload/importer.rb
- Added method `create_content_blocks` to content service 
- Add the ability to pass a `default_user_id` to the importer that you can use to fill in the required user associations when importing data.
=> Content Blocks import

CHANGELOG.md, lib/dradis/plugins/content_service/content_blocks.rb, lib/dradis/plugins/gem_version.rb
The `#all_content_blocks` method will now return alphabetically ordered Content Blocks by default.
=> Content blocks alpha

CHANGELOG.md, lib/dradis/plugins/content_service/issues.rb, lib/dradis/plugins/content_service/nodes.rb, lib/dradis/plugins/content_service/notes.rb, lib/dradis/plugins/content_service/properties.rb
Instead of relying on `set_project_scope` elsewhere, we're going to fetch the records using the right project-based relationships.
=> Update the ContentService to go through the :project to access content

lib/dradis/plugins/thor_helper.rb
Assign a default project id (`Project.new`) to the `task_options` in CE. In Pro, this does nothing as the method is overridden.
=> Add default project to task options

lib/dradis/plugins/content_service/issues.rb, lib/dradis/plugins/content_service/nodes.rb
Currently, the content service is creating nodes without a `project` which makes them invalid. This change makes the node inherit the project id from its parent to make it valid.
=> Add project id when creating nodes

CHANGELOG.md, lib/dradis/plugins/content_service/nodes.rb, lib/dradis/plugins/gem_version.rb
In some cases (CE) `node.project_id` does not exist.
We could just add to the model:
```
def project_id
project.id
end
```
But then some magic methods may fail: `parent_node.find_or_create_by(project_id: ...)` because they try to use the database `node.project_id` column, that still does not exist.
So in this solution we check if the node has `project_id` available in the dradis-plugins content-service.
=> `Node#project_id` does not always exist

lib/dradis/plugins/gem_version.rb
We will not be version bumping the non-tagged master changes until we release v1.15.0.
As per new version bumping guidelines. Master may contain code that is between versions.
=> Remove rc versioning

CHANGELOG.md, Gemfile, lib/dradis/plugins/upload/base.rb
This branch is needed for the Rails/Ruby upgrade ongoing. [Module#parent has been deprecated](https://github.com/rails/rails/pull/34051) and our use of the old method makes pretty much _every_ plugin initialization raise warnings.
=> Update Module#parent usage for deprecations

CHANGELOG.md, lib/dradis/plugins/content_service/evidence.rb
Before this change uploading the same file twice would result in a single set of Issues, but duplicate Evidence all over.
With this PR we're checking each Evidence, if an exact match is already found (same Issue, Content, and Node), then we don't insert it again.
=> ContentService#create_evidence - Avoid dup Evidence

CHANGELOG.md, lib/dradis/plugins/upload/base.rb, lib/dradis/plugins/upload/importer.rb
Add a base method for all upload plugins to offer a template_names mapping.
=> Plugin template names

lib/dradis/plugins/gem_version.rb
Need to bump version to 4.6.1 so that it can be published to RubyGems, as 4.6.0 needed to be taken down for merge fix
=> Bump version to 4.6.1

lib/dradis/plugins/content_service/content_blocks.rb
With the introduction of the state column for issues/content blocks, we want to make sure that the state can be exported and imported along with the project.
**Proposed solution**
Implement an import/export V4 that adds the state attribute.
=> Add state for content blocks

CHANGELOG.md, lib/dradis/plugins/content_service/issues.rb, lib/dradis/plugins/gem_version.rb
Uploading a tool output can sometimes not deduplicate a finding causing the same finding to appear in the project.
This happens because the issue_cache in the dradis-plugins only pulls the published issues.
**Proposed solution**
Pull all the issues in a project for the issue_cache.
=> Fix deduplication

CHANGELOG.md, dradis-plugins.gemspec, lib/dradis/plugins.rb, lib/dradis/plugins/configurable.rb, lib/dradis/plugins/settings.rb, lib/dradis/plugins/settings/adapters/db.rb, lib/dradis/plugins/settings/adapters/encrypted_configuration.rb, spec/engine_spec.rb, spec/lib/dradis/plugins/content_service/boards_spec.rb, spec/lib/dradis/plugins/settings/adapters/encrypted_configuration_spec.rb, spec/settings_spec.rb
Decouple settings from the bakcend used to store them. Extract the default storage to a DB adapter. Include a yet-to-be implemented EncryptedConfiguration adapter.
=> Encrypted Settings: Initial steps

app/controllers/dradis/plugins/export/base_controller.rb
With the removal of the Dradis export#create action, the responsibility to call track_usage in Pro has now been moved to the export addons. We're adding it to the Export::BaseController so that this tracking does not need to be explicitly called.
=> Add Ahoy analytics tracking

app/controllers/dradis/plugins/export/base_controller.rb
Include ProjectScoped in export/base_controller so that track_Export can fetch project and associated records to build Ahoy event
=> Include ProjectScoped in export/base_controller

lib/dradis/plugins/gem_version.rb, lib/dradis/plugins/templates/migrate_templates.rb
We need to allow migration of blank fields from .template files to mapping fields. Since blank mapping field content is not permitted, we are replacing the blank content with a message
=> Replace blank field content with helpful message on template migration to mappings

spec/support/spec_macros.rb
Add spec macros so that spec setup methods can be used in integration specs
Add `stub_content_service` method to spec macros
- ~[ ] Added a CHANGELOG entry~
- ~[ ] Added specs~
=> Add spec macros

lib/dradis/plugins/settings/adapters/db.rb
Having an engine in the main app Gemfile.plugins causes `db:prepare` to fail since we are checking if `engine.enabled?` when the engine is loaded. When the db doesn't exist yet, this check raises an error
This fix ensures that the db is ready before checking whether the engine is enabled
1. In the main app, drop your db `./bin/rails db:drop`
2. Point your Gemfile.plugins to your local repo for any integration ex `gem 'integration', path: ../<integration_name>`
3. Run `./bin/rails db:prepare` and assert that it succeeds
~- [ ] Added a CHANGELOG entry~
~- [ ] Added specs~
=> Guard Configuration check to fix error on db:prepare when engines are loaded

app/controllers/concerns/dradis/plugins/persistent_permissions.rb
Rename strong params from `permissions_params` to `permission_params`
=> Use permission_params for the strong param naming

CHANGELOG.md, app/controllers/concerns/dradis/plugins/exportable.rb, app/controllers/dradis/plugins/export/base_controller.rb
Moved shared export functionality to concern so it can be used by multiple export-related controllers including `export/base_controller` and the Dradis Pro API
=> Add `Exportable` concern

CHANGELOG.md, app/controllers/dradis/plugins/export/base_controller.rb
Currently we're tracking the 'report.exported' ahoy event in the #show action of any controller that extends `Export::BaseController`
We don't need to double track, and tracking this on #create is enough
=> Don't track `report.exported` event in #show action
